version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/node:16.15.0
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: "yarn"
      - run:
          name: "Lint"
          command: "yarn lint"
  build:
    docker:
      - image: cimg/node:16.15.0
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: "yarn"
      - run:
          name: "Build"
          command: "yarn build"

workflows:
  noom-workflow:
    jobs:
      - lint
      - build
